[workspace]
members = [".", "crates/ruminac", "crates/rmvm", "crates/rmpack"]
exclude = ["crates/rmpack/stub"]
resolver = "2"

[workspace.package]
version = "1.3.0"

[package]
name = "rumina"
version.workspace = true
edition = "2024"
description = "Lamina language compatible interpreter written in rust"
license = "MPL-2.0"
default-run = "rumina-cli"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "rumina-cli"
path = "src/main.rs"

[dependencies]
rand = "^0.10.1"
chrono = "0.4.44"
num = "0.4.3"
pathdiff = "0.2.3"
hex = "0.4.3"
base64 = "0.22.1"
rayon = "1.12.0"
rustc-hash = "2.1.2"
malachite-q = "0.9.1"
malachite-nz = "0.9.1"
malachite-base = "0.9.1"
mathcore = "0.3.1"
lazy_static = "1.5.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ctrlc = "^3.5.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "^0.2.121"
getrandom = { version = "^0.4.2", features = ["wasm_js"] }

[dev-dependencies]
criterion = "^0.8.2"
