[package]
name = "rmpack"
version.workspace = true
edition = "2024"
description = "Rumina Packager"
license = "LGPL-2.1"

[[bin]]
name = "rmpack"
path = "src/main.rs"

[dependencies]
rumina = { path = "../.." }
serde_json = "1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ctrlc = "^3"
